paths:
  main_folder: ../example_data/csv_synthea500
  output_dir: ../data/formatted/synthea500
  file_type: csv

preprocessor:
  _target_: preprocessors.synthea.SyntheaPrepocessor
  _recursive_: false

concepts:
  diagnose:
    snomed:
      filename: conditions.csv
      names: [TIMESTAMP, PID, ADMISSION_ID, CONCEPT,]
      usecols: [0, 2, 3, 4]

  medication:
    administered:
      filename: medications.csv
      names: [TIMESTAMP, PID, ADMISSION_ID, CONCEPT, RESULT]
      usecols: [0, 2, 4, 5, 9]

admissions:
  admission:
    filename: medications.csv
    names: [TIMESTAMP, PID, ADMISSION_ID, CONCEPT]
    usecols: [0, 2, 4, 5]

patients_info:
  all:
    filename: patients.csv
    names: [PID, BIRTHDATE, DEATHDATE,RACE, ETHNICITY, GENDER]
    usecols: [0, 1, 2, 12, 13, 14]
      